id: I5B85A064
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-04-06T08:45:26+00:00'
last_modified: '2022-06-16T05:25:52.765309+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20272
  title: ཧྥ་རན་སིར་ཉར་བའི་ཏུན་ཧོང་ཡིག་རྙིང་ཤོག་དྲིལ་བཤུས་ཡིག་ཕྱོགས་བསྒྲིགས། དེབ་དང་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    0F50:
      image_group_id: I8LS20274
      title: ''
      total_pages: ''
      order: 1
      base_file: 0F50.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
